apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: container-pubsub
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: container-pubsub
      name: container-pubsub
    spec:
      containers:
        - name: container-pubsub
          image: "gcr.io/google.com/container-pubsub/container_pubsub"
          env:
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secret/cloud.google.com/service-account.json"
          volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
      volumes:
        - name: "service-account"
          secret: 
            secretName: "service-account"