apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gcp-pubsub
  labels:
    app: gcp-pubsub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-pubsub
  template:
    metadata:
      labels:
        app: gcp-pubsub
    spec:
      containers:
      - name: gcp-pubsub
        image: gcr.io/google.com/container-pubsub/gcp-pubsub
        ports:
        - containerPort: 80